### ISSUE TITLE
Luma3DS crash when trying to back up  a save from Paper Mario: Sticker Star

### ISSUE THREAD

**Issue by Igetin** [BernardoGiordano/Checkpoint#109]
* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Home Menu (Luma3DS)
* System version: 11.6.0
* Checkpoint version: 3.2.0
* Expected behaviour: The backup should be created successfully without errors.
* Encountered behavior: Luma3DS crashes on creating a backup for the game.
* Steps to reproduce:
  * Launch Checkpoint
  * Try to create a save backup from Paper Mario: Sticker Star

![Luma crash screen](https://user-images.githubusercontent.com/14016863/41619204-0adfa3c4-740e-11e8-9166-41b554887507.png)

I'm using the PAL version of the game, and the problem occurs on both physical and digital versions. The backup does get created despite the crash, but when that backup is restored, it doesn't seem to actually affect the game's save (it's the same as before restoring). Restoring this faulty backup does not crash Checkpoint nor Luma3DS.

Luma's crash dump & the backup created by Checkpoint: [checkpoint_pm_crash.zip](https://github.com/BernardoGiordano/Checkpoint/files/2116604/checkpoint_pm_crash.zip)

**Comment by jtiddle** [comment]
The only way I've managed to get around this error is by formatting the SD card. I had the exact same problem with Animal Crossing New Leaf. I'm not too sure but I think Luma has trouble reading data once checkpoint has exported saved data. 

I hope you made backups of your SD card data BEFORE you installed CFW because this makes the process easier. Also, you mentioned you had a back-up sys nand which is great as you will not have to back it up again.

 You can get the game working again it is not bricked. (I made a guide for myself a while ago as I thought I had altered something in the sysnand which would not make my game playable)

From my own experience I had to first uninstall my cfw [through this link](https://3ds.hacks.guide/uninstall-cfw.html) 

Once I realised that even after uninstalling my CFW that the game still had an error and would not start I did this >>>>>>

1. Remove the SD card from the system while the power is off.
2. Insert the game and turn the power on.
3. The system will start with no SD card and will look similar to a formatted system.
4. Start up the game and it should load normally.
5. Power off the system and re-insert the SD card.
6. Power on the system and start up the game. If there is an error, this confirms the system is not the issue. 
7. Power off the system and remove the SD card from the system. 
8. Insert the SD card into a PC and cut/paste the contents into a back-up folder (you may have images you want to keep)
9. Format the SD card in file explorer (FAT32)
10. Re-insert the SD card into the system and power on. Allow it to download the necessary components.
11. Start-up your game... it should now play with an SD card inserted!

Backup your SD card that is formatted, unfortunately if you did not backup before you installed CFW, the save files from digital titles may be lost but I've heard there are ways of digging through .sav files on your SD card to find them.

Obviously after this if you want to continue using CFW you have to reinstall. However, it will take less time seedmining or whatever method you used to get CFW on your system as you may have backed up your files when injecting the firmware.

If all is successful, you should have CFW and your game should be playable again. BEFORE you start using checkpoint again backup your entire SD card in case you have the same problem again. This also saves time deleting CFW folders if you want to remove it again.

Once CFW is back on your system please please back it up! Back up your entire SD! I made this mistake and I had to format my SD card and I had to reinstall all my titles and themes again!

I hope someone has a better method that isn't as long winded as this because I tried a lot of ways and I couldn't get it to work...

**Comment by Igetin** [comment]
@jtiddle You misunderstood the issue. I'm not having any kind of problems with my CFW setup or the game. This issue is about Checkpoint not exporting that specific game's save file correctly, which results in a crash, requiring a reboot. My system and game are completely fine.

**Comment by BernardoGiordano** [comment]
Can you test with this build and report if it now works? https://www.dropbox.com/s/cq5hcyrrdq3dj8s/Checkpoint.cia?dl=0

**Comment by Igetin** [comment]
Using that build, Checkpoint succeeded in backing up the save without crashing. Restoring that backup was also successful. But when launched, the game said “File is corrupted. Formatting file…”, which resulted in three empty save slots. My file had the first slot in use.

I tested a few other cases, and it seems that the game interprets the restored save file as corrupt _only_ if the backup didn't have all three save slots in use. In other words, restoring a backup save file that has only 0, 1 or 2 slots in use results in a corrupt save file, while restoring one that had all 3 save slots in use results in all of the slots working correctly. With “in use”, I mean that the game has been started on that slot and played to a point where saving occurs.

Just in case, here are the backups created by Checkpoint: [checkpoint_pm_files.zip](https://github.com/BernardoGiordano/Checkpoint/files/2225008/checkpoint_pm_files.zip)

Hopefully this helps.

**Comment by BernardoGiordano** [comment]
That edge case is probably not Checkpoint's fault, or, I don't really know how could I handle that. Does it work with other save managers?

**Comment by Igetin** [comment]
I tried JKSM's [latest release](https://github.com/J-D-K/JKSM/releases/tag/07%2F18%2F2018). Like with Checkpoint, restoring save files with 3 slots in use get restored without problems. Restoring files with 0, 1 or 2 slots in use produce an error: “There was an error opening the file for writing.” But when launching the game, a different message (than with Checkpoint) is shown: “Creating file… File Created.” Then it goes to the save slot select screen, and all of the slots have been restored. So JKSM does restore the slots despite its error and the game's message.

The slot files (e.g. pm4_0.bin) created by both managers are identical if the slot is in use, but the slot files created from empty slots have different checksums.

**Comment by BernardoGiordano** [comment]
Can you send me both version of the files?

**Comment by dragaron** [comment]
Just posting to provide more data that will hopefully help you to identify the problem.  I have the exact same issue with Checkpoint v3.4.0 and Paper Mario on both a US 11.5.0-38U and Japanese (region changed) 11.5.0-38U, both with Luma3DS v9.0.  I have 32 other games installed that backup just fine on both systems.  Other than this issue, Checkpoint is awesome and my most preferred save backup manager.  Thanks for the hard work, BernardoGiordano!

**Comment by BernardoGiordano** [comment]
Can you test using this build? https://www.dropbox.com/s/joowr7w45mpaelx/Checkpoint.cia?dl=0

**Comment by Igetin** [comment]
Using that build, both backing up and restoring seem to work properly without any kind of errors or specials messages in-game, regardless of the amount of used slots in the backup. I tested on both physical and digital versions of the game.

**Comment by BernardoGiordano** [comment]
This is considered fixed then

**Comment by dragaron** [comment]
Not quite yet...  Did you test this personally, programmer?  Because in a matter of 90 seconds, I encountered the exact same error with the revised edition of Checkpoint (by installing 3.4.1, and then saving the game through Checkpoint, loading/playing the actual game, adjusting the game, re-saving, and then reloading Checkpoint's backup).  Therefore, I personally am still having issues with Paper Mario. I just backed up a save using Checkpoint 3.4.1, and then moved a few spaces (in the game) and then re-saved, quit the game, reloaded Checkpoint, restored said backed up save, and then had the typical "File is corrupted. Re-creating file." message followed by a cleared (deleted) save file.  Lost my save through this.  Just 90 seconds of quality control could have prevented that...

**Comment by Igetin** [comment]
I tested version 3.4.1 briefly (didn't try all slot combinations), and it works for me. The created files are identical to those of the test build's.

Can you provide more information? Which slots were in use when you backed up via Checkpoint? Are you using the physical version of the game?

**Comment by Nemris** [comment]
I found a workaround for Sticker Star detecting and wiping a restored backup where not all slots are occupied.

In GodMode9 or any file manager, navigate to the directory where Checkpoint keeps its PMSS backups - in my case, `sdroot:/3ds/Checkpoint/saves/0x00A5F PAPER MARIO` - and identify the backup you want to restore.

Then, copy the directory containing the `pm4_X.bin` files and give it a distinct name. The .bin files within represent the slots, and you need to replace any that are completely zeroed by any that are nonzero. The SHA-256 hash for enpty slots is `ACF8E8273AB1230BE24471081312AC3A77DE2D692E1863C91EFFE5655532FBB1`.
This will effectively duplicate some of your slots.

Lastly, restore this new backup with Checkpoint, launch PMSS and remove the duplicated slots you created from within the save slot selection menu.
