### ISSUE TITLE
Checkpoint isn't naming some of my save folders with the games name.

### ISSUE THREAD

**Issue by Primeey** [BernardoGiordano/Checkpoint#117]
* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Launching cfw via Hekate by accessing RCM with a jig
* System version: 5.1.0
* Checkpoint version: 3.3.0
* Expected behaviour: The folder for my Crash Bandicoot N. Sane Trilogy save should be named 0x0100D1B006744000 Crash Bandicoot N. Sane Trilogy and the folder for Rocket League should be named 0x01005EE0036EC000 Rocket League
* Encountered behavior: Crash Bandicoot N. Sane Trilogy is named 0x0100D1B006744000 0x0100D1B006744000 and Rocket League is named 0x01005EE0036EC000 0x01005EE0036EC000
* Result code (if available):
* Steps to reproduce:
  * Launch Checkpoint and backup either Rocket League or Crash Bandicoot N. Sane Trilogy
  * Check the name of the folders

**Comment by kade-robertson** [comment]
I believe this is the intended behaviour, based on [this](https://github.com/BernardoGiordano/Checkpoint/blob/master/switch/source/title.cpp#L89). It's because those games have a trademark symbol in their name, and because it's considered an unsafe/invalid character it just uses the TitleID instead.

**Comment by fennectech** [comment]
Rocket league doesnt have any trademarked symbols

**Comment by kade-robertson** [comment]
The function `StringUtils::containsInvalidChar(name)` indicates the character is invalid (as per the link in my first comment). Checking out the [implementation](https://github.com/BernardoGiordano/Checkpoint/blob/e5fd2f04ddc680da6b8931dc2e58b017af993e4a/common/common.cpp#L43), anything non-ASCII is considered invalid probably because it's easier for @BernardoGiordano to not display UTF-8 strings at this point?

**Comment by fennectech** [comment]
Can we just strip invalid characters?

**Comment by fennectech** [comment]
SO Rocket league (R) would be stripped to “Rocket League”    And Pokémon Quest  is stripped to Pokemon Quest.

**Comment by kade-robertson** [comment]
Well these are sort of two different scenarios. In the case of trademark/registered symbols, we can probably just delete or blank them out. Replacing accented characters with their non-accented parts is probably a bit annoying but can be done, as you would have to map each case to it's 'base' form (assuming there's nothing already available that does this without being too huge of a dependency).

Forget what I said earlier about UTF-8, this limitation seems reasonable at the current time because FAT32 cannot support these characters in the folder names. exFAT would/should have no issue with these characters though -- maybe if Checkpoint looks to see if the MicroSD is formatted as exFAT the invalid character check can be removed? It seems from exFAT spec that it can support the vast majority of the UTF-16 code points.

**Comment by fennectech** [comment]
We could compile a list of accented characters for English alphabet and strip characters that dont conform.

**Comment by fennectech** [comment]
And as for accented haricters most of them have ascii alternatives.

**Comment by fennectech** [comment]
We need to maintain Support for fat32 as many dont use exfat becuase of its increased fragility.

**Comment by garoxas** [comment]
still happens on Checkpoint 3.4.1

I was using Checkpoint 3.4.0 and it's correctly use the game name **0x01007330027EE000 ULTRA STREET FIGHTER   II The Final Challengers** (with non supported characters omitted as expected)
but after upgrade to 3.4.1, now it's using **0x01007330027EE000 0x01007330027EE000**
