### ISSUE TITLE
[Recommendation] Split 3DS and Switch in separate repos (or branches)

### ISSUE THREAD

**Issue by Favna** [BernardoGiordano/Checkpoint#73]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

* [ ] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [x] Feature request

### Error details

N.A.
  
### Feature request details

Currently the Switch and 3DS code is all bundled up in folders. This works for while the Switch version isn't massively distributed just yet, but if 3DS save editing and the popularity of Checkpoint is anything to by then it will only be a matter of time until it is. The bundling up causes a certain feeling of chaotic file system in the README and Repo files and I'd say this is especially noticeable in the README.

This concern has no immediate priority, but I do think that going forward it would be better if the versions were distinctly split. If you're going for the separate repo approach I would recommend keeping this as named `Checkpoint` since it would otherwise break any links to this repo from posts on other sites. The other repo can be called `Checkpoint-Switch`, or maybe some other new fancy name. I'm not the best with names but just pulling something from my hat I think something towards `Frontier` / `Frontierpoint` / `Controlpoint` would be pretty nice and sort of in the same vein as what I assume is referred to with "checkpoint" (that being a checkpoint in a game where progress is *saved*) (discounting `Savepoint` since that's so obvious anyone could come up with it)

**Comment by BernardoGiordano** [comment]
I think that going to separate repos isn't in my current plans, because of at least two reasons:
* lots of code between the 3DS and the Switch version is exactly the same and currently it is just duplicated, but could be placed in shared headers or source files in order to simplify the amount of code written
* I have intention to port Checkpoint to other platforms as well in the future, and having multiple repos for each platform doesn't seem a great idea for me. Also having different branches confuses the less experienced users and they may not find or notice the code they want to look at.

**Comment by Favna** [comment]
Hm yes I can see your point of view for sure, especially given the second one. If you wouldn't mind I may look into reformatting the readme then to make a clearer distinction than just separate paragraphs. That would come in the form of a PR if I do get something figured out. No guarantees though, formatting can only do so much as well, but I do have some ideas. When I get to it I'll hop into the discord server to bounce off some ideas before making the PR.

**Comment by BernardoGiordano** [comment]
Sure, PRs are fine. Keep in contact on Discord in case
